### ISSUE TITLE
Where can i find any decoder lib ?

### ISSUE THREAD

**Issue by Kim-DJIN-Tech** [gs1/gs1-syntax-engine#2]
i am trying do develop and app to read GS1 barcodes, and the only one i can't read is GS1 databar, my app is written in javascript and uses zbar and zxing in parallel, i've tried opencv as wall but no success, i've tested literally hundreds of apps and tools online for gs1 and none of them can read databar except for a japanese app called "添文ナビ"... 
can somebody please help me ? anything could help ....

**Comment by terryburton** [comment]
GS1 does not develop a barcode decoder library and is not able to recommend between third party libraries that do so.

Closing as this is unrelated to the GS1 Syntax Engine.
