### ISSUE TITLE
c-lib: parseSyntaxDictionaryEntry fails on Linux if "gs1-syntax-dictionary.txt" was checked out with \r\n line endings

### ISSUE THREAD

**Issue by RemotelyChaotic** [gs1/gs1-syntax-engine#8]
If the file "gs1-syntax-dictionary.txt" was checked out with \r\n line endings under Linux. the function call parseSyntaxDictionaryEntry fails to parse the file with:

```
*** Failed to parse Syntax Dictionary file: gs1-syntax-dictionary.txt
*** Syntax Dictionary line 106: AI has wrong width
```

This seems to be due to `strtok_r(linebuf, " \t", &saveptr);` returning the \r character on Linux. On Windows there seems to be no issue either way.

It can be circumvented by inserting a comment char at the start of line 106 or checking out with Linux-style line endings.

**Comment by terryburton** [comment]
@RemotelyChaotic Thanks for the report.
